#!/usr/bin/env python3
"""Regenerate the nine Estuary 3 Act 3 walkabout hero images.

Deterministic — byte-identical output on every run. Each scene keeps
the compositional subject of the original hand-authored version
(what the location IS) and rebuilds the rendering through the
2026-07-10 HeroImage ops: dithered gradients, shade, noise, disk,
ring, checker. Palette-per-scene (12-14 colors) so each location
holds its own morning: it is Labor Day, September 1, 1998, and the
marine layer is lifting at different rates all over town.

Also emits library/sprites/shelf_backdrop.json — the cabin wall
behind the slowstock shelf in the 2048 frame story.
"""
import json
import os

W, H = 160, 90
ACT3_DIR = os.path.join(os.path.dirname(__file__), "..", "..",
                        "resources", "games", "vol7", "estuary_3",
                        "sprites", "act3")
LIB_DIR = os.path.join(os.path.dirname(__file__), "..", "..",
                       "resources", "games", "vol7", "library", "sprites")


class Scene:
    """Palette-by-name so nine scenes stay readable."""

    def __init__(self, sid, notes):
        self.id = sid
        self.notes = notes
        self.palette = []
        self._idx = {}
        self.layers = []

    def c(self, name, hexv=None):
        if name not in self._idx:
            if hexv is None:
                raise KeyError("color %r not yet defined in %s" % (name, self.id))
            self._idx[name] = len(self.palette)
            self.palette.append(hexv)
        return self._idx[name]

    def add(self, op, **kw):
        d = {"op": op}
        d.update(kw)
        self.layers.append(d)

    def doc(self):
        return {"id": self.id, "notes": self.notes, "w": W, "h": H,
                "palette": self.palette, "layers": self.layers}


# ── shared vocabulary ────────────────────────────────────────────

def spruce(s, x, base_y, height, color):
    """Coastal conifer silhouette: two stacked triangles + trunk."""
    half = max(3, height // 3)
    s.add("poly", points=[[x, base_y - height], [x - half, base_y - height // 3],
                          [x + half, base_y - height // 3]], color=color)
    s.add("poly", points=[[x, base_y - (height * 3) // 4],
                          [x - half - 2, base_y], [x + half + 2, base_y]],
          color=color)
    s.add("vline", x=x, y_range=[base_y, base_y + 2], color=color)


def figure(s, x, base_y, color, h=12):
    """Small standing person, feet at base_y."""
    s.add("rect", xywh=[x - 1, base_y - h + 3, 3, h - 3], color=color)
    s.add("dot", xy=[x, base_y - h + 1], size=2, color=color)


def bike(s, x, base_y, frame_color, wheel_color):
    """Side-view bicycle, wheels on base_y."""
    s.add("ring", xy=[x - 4, base_y - 3], r=3, color=wheel_color)
    s.add("ring", xy=[x + 4, base_y - 3], r=3, color=wheel_color)
    s.add("polyline", points=[[x - 4, base_y - 3], [x, base_y - 7],
                              [x + 4, base_y - 3], [x, base_y - 3],
                              [x - 4, base_y - 3]], color=frame_color)
    s.add("vline", x=x + 4, y_range=[base_y - 9, base_y - 3], color=frame_color)


# ── the nine locations ───────────────────────────────────────────

def pier():
    s = Scene("pier", "The pier at 9 AM. Marine layer half-lifted. A figure "
                      "at the far end. Water going flat to the horizon. "
                      "Generated by gen_estuary3_act3_scenes.py.")
    ink = s.c("ink", "#141828")
    fog = s.c("fog", "#d8dce0")
    sky = s.c("sky", "#a8b8c4")
    sky_hi = s.c("sky_hi", "#c8d4d8")
    water_dk = s.c("water_dk", "#3a4a58")
    water = s.c("water", "#4a5866")
    water_lt = s.c("water_lt", "#8090a0")
    deck = s.c("deck", "#645848")
    deck_lt = s.c("deck_lt", "#847660")
    piling = s.c("piling", "#463c30")
    fig = s.c("fig", "#2a2a30")
    gull = s.c("gull", "#e8ecf0")

    s.add("vgrad", y_range=[0, 42], stops=[fog, sky_hi, sky])
    s.add("shade", xywh=[0, 20, 160, 14], color=fog, amount=0.35)   # layer lifting
    s.add("vgrad", y_range=[42, 90], stops=[water_lt, water, water_dk])
    s.add("hline", y=42, x_range=[0, 160], color=fog)               # horizon
    s.add("noise", xywh=[0, 46, 160, 30], color=water_lt, density=0.06, seed=5)
    s.add("noise", xywh=[0, 44, 160, 10], color=fog, density=0.03, seed=9)
    # Deck in perspective — wide at the bottom, narrowing to the end.
    s.add("poly", points=[[0, 90], [160, 90], [150, 46], [60, 46]], color=deck)
    s.add("polyline", points=[[0, 90], [60, 46]], color=ink)
    s.add("polyline", points=[[160, 90], [150, 46]], color=ink)
    for i, y in enumerate((52, 60, 70, 82)):                        # plank seams
        x0 = 30 - i * 10
        s.add("hline", y=y, x_range=[max(0, x0), min(160, 160 - x0 // 2)], color=ink)
    s.add("shade", xywh=[0, 46, 160, 44], color=deck_lt, amount=0.15)
    # Railing + pilings, shrinking with distance.
    for i, x in enumerate((20, 44, 66, 86, 104, 120, 134)):
        top = 46 - i  # rail rises slightly toward the eye? no — sinks with distance
        s.add("vline", x=x, y_range=[46 - 14 + i, 46 + 30 - i * 4], color=piling)
    s.add("polyline", points=[[20, 32], [134, 40]], color=piling)   # rail line
    figure(s, 146, 46, fig, h=10)
    s.add("dot", xy=[100, 22], size=1, color=gull)
    s.add("dot", xy=[104, 24], size=1, color=gull)
    return s


def tide_gate():
    s = Scene("tide_gate", "The tide gate at the mouth of the estuary. "
                           "Concrete abutments, steel gate at PARTIAL, water "
                           "moving through. The 2 AM customer in daylight, "
                           "grey work jacket, binoculars. Generated by "
                           "gen_estuary3_act3_scenes.py.")
    ink = s.c("ink", "#141820")
    sky = s.c("sky", "#a8b0b8")
    sky_hi = s.c("sky_hi", "#c8ccd0")
    marsh = s.c("marsh", "#8a8878")
    marsh_dk = s.c("marsh_dk", "#6a6a58")
    water = s.c("water", "#3a4048")
    water_lt = s.c("water_lt", "#565e68")
    conc = s.c("conc", "#606870")
    conc_lt = s.c("conc_lt", "#848a92")
    steel = s.c("steel", "#4a5058")
    grass = s.c("grass", "#3a4838")
    fig = s.c("fig", "#3c4044")

    s.add("vgrad", y_range=[0, 52], stops=[sky_hi, sky])
    s.add("noise", xywh=[0, 8, 160, 20], color=sky_hi, density=0.05, seed=4)
    s.add("hband", y_range=[52, 66], color=marsh)
    s.add("noise", xywh=[0, 52, 160, 14], color=marsh_dk, density=0.2, seed=6)
    s.add("noise", xywh=[0, 52, 160, 14], color=grass, density=0.1, seed=8)
    s.add("vgrad", y_range=[66, 90], stops=[water_lt, water])
    s.add("noise", xywh=[0, 68, 160, 20], color=water_lt, density=0.08, seed=12)
    # Flow lines downstream of the gate.
    for y in (72, 78, 84):
        s.add("hline", y=y, x_range=[54, 106], color=water_lt)
    # Abutments — concrete with a lit face and a shaded face.
    for x in (10, 130):
        s.add("rect", xywh=[x, 30, 20, 46], color=conc)
        s.add("rect", xywh=[x, 30, 6, 46], color=conc_lt)
        s.add("noise", xywh=[x, 30, 20, 46], color=conc_lt, density=0.06, seed=x)
        s.add("vline", x=x, y_range=[30, 76], color=ink)
        s.add("vline", x=x + 19, y_range=[30, 76], color=ink)
        s.add("hline", y=30, x_range=[x, x + 20], color=ink)
    # Steel gate, dropped to PARTIAL.
    s.add("rect", xywh=[30, 32, 100, 22], color=steel)
    s.add("shade", xywh=[30, 32, 100, 22], color=ink, amount=0.15)
    for y in (32, 40, 46, 54):
        s.add("hline", y=y, x_range=[30, 130], color=ink)
    s.add("vgrad", y_range=[54, 66], x_range=[30, 130],
          stops=[water_lt, water])                                   # gap under gate
    s.add("rect", xywh=[40, 18, 32, 8], color=conc_lt)
    s.add("text", xy=[42, 20], s="PARTIAL", color=ink)
    # The 2 AM customer, watching the water.
    figure(s, 89, 80, fig, h=14)
    s.add("dot", xy=[89, 72], size=1, color=ink)                     # binoculars
    return s


def aandahl_house():
    s = Scene("aandahl_house", "The Aandahl house. Pale-blue single-story, "
                               "two kids' bikes on the porch, hummingbird "
                               "feeder, Mr Aandahl in the yard. Generated by "
                               "gen_estuary3_act3_scenes.py.")
    ink = s.c("ink", "#12181e")
    sky = s.c("sky", "#c8dcd8")
    sky_hi = s.c("sky_hi", "#e4ece8")
    house = s.c("house", "#7a94b0")
    house_lt = s.c("house_lt", "#9ab0c6")
    roof = s.c("roof", "#5a4838")
    roof_lt = s.c("roof_lt", "#6e5a46")
    win = s.c("win", "#c8a860")
    lawn = s.c("lawn", "#3a5a3a")
    lawn_lt = s.c("lawn_lt", "#4c6e44")
    trim = s.c("trim", "#e8e8e0")
    spruce_c = s.c("spruce", "#2a4030")
    fig = s.c("fig", "#4a4238")
    flower = s.c("flower", "#c05848")

    s.add("vgrad", y_range=[0, 62], stops=[sky_hi, sky])
    s.add("noise", xywh=[0, 6, 160, 18], color=sky_hi, density=0.06, seed=2)
    spruce(s, 10, 62, 34, spruce_c)
    spruce(s, 152, 62, 28, spruce_c)
    s.add("vgrad", y_range=[62, 90], stops=[lawn_lt, lawn])
    s.add("noise", xywh=[0, 64, 160, 26], color=lawn, density=0.15, seed=14)
    s.add("noise", xywh=[0, 70, 160, 20], color=lawn_lt, density=0.08, seed=15)
    # House — lit face left, shade right, trim under the eave.
    s.add("rect", xywh=[20, 40, 120, 32], color=house)
    s.add("rect", xywh=[20, 40, 46, 32], color=house_lt)
    s.add("poly", points=[[20, 40], [80, 22], [140, 40]], color=roof)
    s.add("poly", points=[[20, 40], [80, 22], [50, 40]], color=roof_lt)
    s.add("polyline", points=[[20, 40], [80, 22], [140, 40]], color=ink)
    s.add("hline", y=40, x_range=[20, 140], color=trim)
    # Windows with frames + half-drawn curtains.
    for wx in (42, 84, 110):
        s.add("rect", xywh=[wx, 50, 12, 12], color=win)
        s.add("rect", xywh=[wx, 50, 12, 4], color=trim)
        s.add("hline", y=50, x_range=[wx, wx + 12], color=ink)
        s.add("hline", y=61, x_range=[wx, wx + 12], color=ink)
        s.add("vline", x=wx, y_range=[50, 62], color=ink)
        s.add("vline", x=wx + 11, y_range=[50, 62], color=ink)
    # Door + porch.
    s.add("rect", xywh=[66, 52, 16, 20], color=roof)
    s.add("dot", xy=[79, 62], size=1, color=win)
    s.add("rect", xywh=[60, 70, 28, 3], color=trim)                 # porch slab
    s.add("shade", xywh=[20, 72, 120, 4], color=ink, amount=0.3)    # house shadow
    # Two kids' bikes leaned by the porch.
    bike(s, 30, 70, ink, fig)
    bike(s, 46, 71, ink, fig)
    # Hummingbird feeder off the eave.
    s.add("vline", x=126, y_range=[40, 46], color=ink)
    s.add("dot", xy=[126, 47], size=2, color=flower)
    # Mr Aandahl in the yard.
    figure(s, 106, 84, fig, h=13)
    s.add("noise", xywh=[10, 76, 40, 12], color=flower, density=0.04, seed=21)
    return s


def bookstore():
    s = Scene("bookstore", "Amelia Rocha's bookstore. Brick front, warm "
                           "window with the April display still up, BACK IN "
                           "15 MINUTES in her handwriting. Generated by "
                           "gen_estuary3_act3_scenes.py.")
    ink = s.c("ink", "#1a0e08")
    sky = s.c("sky", "#c8c4b4")
    brick = s.c("brick", "#7a4028")
    brick_lt = s.c("brick_lt", "#8e5034")
    glass = s.c("glass", "#c8a880")
    glass_deep = s.c("glass_deep", "#a08058")
    frame = s.c("frame", "#3a2818")
    walk = s.c("walk", "#a8a090")
    walk_dk = s.c("walk_dk", "#8a8274")
    sign = s.c("sign", "#e8dcc0")
    book_r = s.c("book_r", "#a04830")
    book_b = s.c("book_b", "#3a5468")
    book_g = s.c("book_g", "#4a6444")
    awn = s.c("awn", "#5a3424")

    s.add("vgrad", y_range=[0, 18], stops=[sky, sky])
    s.add("hband", y_range=[0, 18], color=sky)
    # Brick face — checker gives the coursing, noise weathers it.
    s.add("rect", xywh=[10, 12, 140, 50], color=brick)
    s.add("checker", xywh=[10, 12, 140, 50], colors=[brick, brick_lt], cell=3)
    s.add("noise", xywh=[10, 12, 140, 50], color=brick, density=0.35, seed=31)
    s.add("hline", y=12, x_range=[10, 150], color=ink)
    # Awning over the window.
    s.add("rect", xywh=[20, 24, 52, 5], color=awn)
    s.add("shade", xywh=[20, 29, 52, 3], color=ink, amount=0.4)
    # Display window — warm light, book spines standing in it.
    s.add("rect", xywh=[22, 30, 48, 26], color=frame)
    s.add("vgrad", y_range=[32, 54], x_range=[24, 68], stops=[glass, glass_deep])
    xs = [26, 30, 33, 37, 41, 44, 48, 52, 55, 59, 63]
    cols = [book_r, book_b, book_g]
    for i, bx in enumerate(xs):
        bh = 8 + (i * 5) % 4
        s.add("rect", xywh=[bx, 52 - bh, 2, bh], color=cols[i % 3])
    s.add("hline", y=52, x_range=[24, 68], color=ink)                # shelf
    # BOOKS sign.
    s.add("rect", xywh=[74, 20, 24, 7], color=frame)
    s.add("text", xy=[77, 21], s="BOOKS", color=sign)
    # Door with the note taped inside the glass.
    s.add("rect", xywh=[90, 28, 28, 34], color=frame)
    s.add("rect", xywh=[93, 31, 22, 28], color=glass_deep)
    s.add("rect", xywh=[96, 40, 16, 9], color=sign)
    s.add("text", xy=[97, 41], s="BACK", color=ink)
    s.add("dot", xy=[114, 46], size=1, color=ink)                    # knob
    # Sidewalk with joints and shade at the wall base.
    s.add("vgrad", y_range=[62, 90], stops=[walk, walk_dk])
    s.add("shade", xywh=[10, 62, 140, 3], color=ink, amount=0.35)
    for jx in (30, 70, 110, 150):
        s.add("vline", x=jx, y_range=[62, 90], color=walk_dk)
    s.add("noise", xywh=[0, 64, 160, 26], color=walk_dk, density=0.06, seed=33)
    return s


def cabin_road():
    s = Scene("cabin_road", "The cabin road turnoff at milepost 214. Gate "
                            "with a chain and the hand-lettered BUILT '79 "
                            "sign. The wagon at the shoulder with ESTUARY 3 "
                            "on the passenger seat. Generated by "
                            "gen_estuary3_act3_scenes.py.")
    ink = s.c("ink", "#0e1408")
    sky = s.c("sky", "#c8c0a8")
    sky_hi = s.c("sky_hi", "#e0d8c0")
    forest = s.c("forest", "#22301a")
    forest_lt = s.c("forest_lt", "#2a3a1c")
    scrub = s.c("scrub", "#5a6a3a")
    road = s.c("road", "#a89a70")
    road_dk = s.c("road_dk", "#8a7c58")
    post = s.c("post", "#4a3c28")
    sign = s.c("sign", "#c8c0a8")
    letter = s.c("letter", "#7a3020")
    wagon = s.c("wagon", "#7a3020")
    cart = s.c("cart", "#c8a860")

    s.add("vgrad", y_range=[0, 50], stops=[sky_hi, sky])
    # Spruce walls both sides of the cut.
    for x in (8, 22, 36, 124, 138, 152):
        spruce(s, x, 58, 30 + (x * 3) % 8, forest)
    for x in (14, 30, 130, 146):
        spruce(s, x, 60, 22 + (x * 5) % 6, forest_lt)
    s.add("hband", y_range=[58, 66], color=scrub)
    s.add("noise", xywh=[0, 58, 160, 8], color=forest_lt, density=0.25, seed=41)
    s.add("hband", y_range=[66, 90], color=forest_lt)
    s.add("noise", xywh=[0, 66, 160, 24], color=scrub, density=0.15, seed=42)
    # The road, gravel-textured, running to the gate.
    s.add("poly", points=[[70, 44], [90, 44], [112, 90], [48, 90]], color=road)
    s.add("noise", xywh=[48, 44, 64, 46], color=road_dk, density=0.12, seed=43)
    s.add("polyline", points=[[70, 44], [48, 90]], color=road_dk)
    s.add("polyline", points=[[90, 44], [112, 90]], color=road_dk)
    for cy, cw in ((52, 1), (62, 2), (74, 2), (86, 3)):              # center dashes
        s.add("rect", xywh=[79, cy, cw, 3], color=road_dk)
    # The gate: posts, two rails, sagging chain.
    s.add("vline", x=58, y_range=[46, 66], color=post)
    s.add("vline", x=59, y_range=[46, 66], color=post)
    s.add("vline", x=101, y_range=[46, 66], color=post)
    s.add("vline", x=102, y_range=[46, 66], color=post)
    s.add("hline", y=52, x_range=[59, 102], color=post)
    s.add("hline", y=58, x_range=[59, 102], color=post)
    s.add("polyline", points=[[59, 54], [80, 58], [101, 54]], color=ink)  # chain
    # BUILT '79, hand-lettered.
    s.add("rect", xywh=[64, 42, 34, 8], color=sign)
    s.add("hline", y=42, x_range=[64, 98], color=ink)
    s.add("text", xy=[66, 44], s="BUILT-79", color=letter)
    # The wagon at the shoulder.
    s.add("rect", xywh=[116, 68, 28, 10], color=wagon)
    s.add("rect", xywh=[120, 63, 18, 5], color=cart)
    s.add("dot", xy=[126, 66], size=2, color=ink)                    # the cart on the seat
    s.add("ring", xy=[122, 80], r=3, color=ink)
    s.add("ring", xy=[138, 80], r=3, color=ink)
    s.add("shade", xywh=[114, 79, 34, 4], color=ink, amount=0.3)
    # Milepost 214.
    s.add("vline", x=30, y_range=[62, 74], color=sign)
    s.add("text", xy=[24, 56], s="214", color=sign)
    return s


def elementary_school():
    s = Scene("elementary_school", "The elementary school playground. "
                                   "Chain-link fence, slide, two swings, "
                                   "marquee reading WELCOME BACK SAM. The "
                                   "kid on the bike outside the fence. "
                                   "Generated by gen_estuary3_act3_scenes.py.")
    ink = s.c("ink", "#100c0a")
    sky = s.c("sky", "#c8ccb0")
    sky_hi = s.c("sky_hi", "#e0e2cc")
    field = s.c("field", "#6a7050")
    field_lt = s.c("field_lt", "#7c8460")
    asphalt = s.c("asphalt", "#8a8a80")
    marquee = s.c("marquee", "#c8ccb0")
    marq_dk = s.c("marq_dk", "#3a3a34")
    metal = s.c("metal", "#4a5666")
    metal_lt = s.c("metal_lt", "#68788c")
    fence = s.c("fence", "#9aA0a0".lower())
    kid = s.c("kid", "#c86040")

    s.add("vgrad", y_range=[0, 56], stops=[sky_hi, sky])
    s.add("noise", xywh=[0, 8, 160, 16], color=sky_hi, density=0.05, seed=51)
    # Marquee on posts.
    s.add("rect", xywh=[18, 34, 124, 12], color=marq_dk)
    s.add("rect", xywh=[20, 36, 120, 8], color=marquee)
    s.add("text", xy=[29, 38], s="WELCOME BACK SAM", color=ink)
    s.add("vline", x=40, y_range=[46, 58], color=marq_dk)
    s.add("vline", x=120, y_range=[46, 58], color=marq_dk)
    # Ground: asphalt apron, then field.
    s.add("hband", y_range=[56, 66], color=asphalt)
    s.add("noise", xywh=[0, 56, 160, 10], color=ink, density=0.03, seed=52)
    s.add("vgrad", y_range=[66, 90], stops=[field_lt, field])
    s.add("noise", xywh=[0, 68, 160, 22], color=field, density=0.15, seed=53)
    # Slide — ladder, chute, shade beneath.
    s.add("vline", x=22, y_range=[52, 78], color=metal)
    s.add("vline", x=25, y_range=[52, 78], color=metal)
    for ly in (56, 61, 66, 71):
        s.add("hline", y=ly, x_range=[22, 26], color=metal_lt)
    s.add("polyline", points=[[25, 52], [44, 74]], color=metal_lt)
    s.add("polyline", points=[[25, 54], [44, 76]], color=metal)
    s.add("shade", xywh=[22, 76, 24, 3], color=ink, amount=0.3)
    # Swing set — A-frame, two chains + seats.
    s.add("polyline", points=[[56, 76], [64, 56], [72, 76]], color=metal)
    s.add("polyline", points=[[92, 76], [84, 56], [76, 76]], color=metal)
    s.add("hline", y=56, x_range=[64, 84], color=metal_lt)
    for cx in (69, 79):
        s.add("vline", x=cx, y_range=[57, 70], color=ink)
        s.add("rect", xywh=[cx - 2, 70, 5, 2], color=metal_lt)
    # Chain-link fence along the front, kid outside it.
    for fx in range(6, 160, 8):
        s.add("vline", x=fx, y_range=[62, 80], color=fence)
    s.add("hline", y=62, x_range=[0, 160], color=fence)
    s.add("hline", y=80, x_range=[0, 160], color=fence)
    s.add("noise", xywh=[0, 63, 160, 17], color=fence, density=0.12, seed=54)
    figure(s, 132, 88, kid, h=11)
    bike(s, 141, 88, ink, metal)
    return s


def kwik_stop_revisit():
    s = Scene("kwik_stop_revisit", "The Kwik Stop in Labor Day morning "
                                   "light, from the lot. Pumps in front, "
                                   "salt-worn siding, the sign warm against "
                                   "a thinning marine layer. Generated by "
                                   "gen_estuary3_act3_scenes.py.")
    ink = s.c("ink", "#1a1a24")
    sky = s.c("sky", "#c8c0a8")
    sky_gold = s.c("sky_gold", "#e0cE9a".lower())
    haze = s.c("haze", "#d4cCb4".lower())
    wall = s.c("wall", "#3a3a48")
    wall_lt = s.c("wall_lt", "#4c4c5c")
    win = s.c("win", "#c8c0a8")
    win_glow = s.c("win_glow", "#e8d8a0")
    sign_y = s.c("sign_y", "#e8c862")
    lot = s.c("lot", "#8a8272")
    lot_dk = s.c("lot_dk", "#6e6858")
    pump = s.c("pump", "#9a8060")
    stripe = s.c("stripe", "#b04038")

    s.add("vgrad", y_range=[0, 55], stops=[sky_gold, sky])
    s.add("shade", xywh=[0, 14, 160, 12], color=haze, amount=0.4)    # marine layer
    s.add("noise", xywh=[0, 6, 160, 10], color=haze, density=0.08, seed=61)
    # Store — siding courses, three windows catching the morning.
    s.add("rect", xywh=[30, 30, 100, 45], color=wall)
    s.add("shade", xywh=[30, 30, 100, 8], color=wall_lt, amount=0.5)
    for sy in range(36, 74, 5):
        s.add("hline", y=sy, x_range=[30, 130], color=ink)
    s.add("hline", y=30, x_range=[30, 130], color=ink)
    for wx in (46, 72, 98):
        s.add("vgrad", y_range=[40, 65], x_range=[wx, wx + 20],
              stops=[win_glow, win])
        s.add("hline", y=40, x_range=[wx, wx + 20], color=ink)
        s.add("vline", x=wx, y_range=[40, 65], color=ink)
        s.add("vline", x=wx + 19, y_range=[40, 65], color=ink)
    s.add("rect", xywh=[76, 65, 12, 10], color=ink)                  # door
    # Sign with a faint glow still on from the night.
    s.add("rect", xywh=[20, 20, 28, 10], color=sign_y)
    s.add("shade", xywh=[17, 17, 34, 16], color=sign_y, amount=0.15)
    s.add("text", xy=[23, 22], s="KWIK", color=ink)
    s.add("vline", x=33, y_range=[30, 40], color=ink)
    # Lot — sun side to shade side, oil stains, one parking stripe.
    s.add("hgrad", x_range=[0, 160], y_range=[75, 90], stops=[lot, lot_dk])
    s.add("hband", y_range=[73, 75], color=lot_dk)
    s.add("noise", xywh=[0, 76, 160, 14], color=ink, density=0.04, seed=62)
    s.add("noise", xywh=[40, 78, 60, 10], color=lot_dk, density=0.15, seed=63)
    s.add("polyline", points=[[16, 90], [28, 78]], color=win)
    # Pumps on their island, hoses looping.
    s.add("rect", xywh=[18, 66, 40, 4], color=lot_dk)                # island
    for px in (22, 40):
        s.add("rect", xywh=[px, 52, 10, 15], color=pump)
        s.add("rect", xywh=[px, 52, 10, 3], color=stripe)
        s.add("vline", x=px, y_range=[52, 67], color=ink)
        s.add("vline", x=px + 9, y_range=[52, 67], color=ink)
        s.add("polyline", points=[[px + 9, 56], [px + 13, 60], [px + 11, 66]],
              color=ink)
    s.add("shade", xywh=[18, 70, 44, 3], color=ink, amount=0.3)
    return s


def mill_office():
    s = Scene("mill_office", "The Weyerhaeuser mill office, closed since "
                             "'96. Fenced yard gone to weed, ghosted sign, "
                             "the sixth window lit. Generated by "
                             "gen_estuary3_act3_scenes.py.")
    ink = s.c("ink", "#100c08")
    sky = s.c("sky", "#88886a")
    sky_dk = s.c("sky_dk", "#6e6e58")
    build = s.c("build", "#6a5838")
    build_dk = s.c("build_dk", "#544628")
    win = s.c("win", "#3a3a3a")
    win_lit = s.c("win_lit", "#c8b060")
    ghost = s.c("ghost", "#78684a")
    fence = s.c("fence", "#4a4438")
    weed = s.c("weed", "#3a2e18")
    weed_lt = s.c("weed_lt", "#5a5030")
    crow = s.c("crow", "#0c0a08")

    s.add("vgrad", y_range=[0, 50], stops=[sky, sky_dk])
    s.add("noise", xywh=[0, 4, 160, 30], color=sky_dk, density=0.08, seed=71)
    # The long office block, weathered.
    s.add("rect", xywh=[20, 24, 120, 34], color=build)
    s.add("shade", xywh=[20, 24, 120, 34], color=build_dk, amount=0.2)
    s.add("noise", xywh=[20, 24, 120, 34], color=build_dk, density=0.1, seed=72)
    s.add("hline", y=24, x_range=[20, 140], color=ink)
    s.add("hline", y=57, x_range=[20, 140], color=ink)
    # Ghosted sign — one tone above the wall, letters almost gone.
    s.add("rect", xywh=[52, 26, 56, 6], color=ghost)
    s.add("text", xy=[57, 27], s="WEYERHSR", color=build)
    # Six windows; the sixth is the lit one.
    for i, wx in enumerate((28, 46, 64, 82, 100, 118)):
        if i == 5:
            s.add("rect", xywh=[wx, 38, 10, 12], color=win_lit)
            s.add("shade", xywh=[wx - 2, 36, 14, 16], color=win_lit, amount=0.2)
        else:
            s.add("rect", xywh=[wx, 38, 10, 12], color=win)
            s.add("vline", x=wx + 5, y_range=[38, 50], color=build_dk)
        s.add("hline", y=38, x_range=[wx, wx + 10], color=ink)
    # Yard gone to weed, fence with sagging rails.
    s.add("vgrad", y_range=[58, 90], stops=[weed_lt, weed])
    s.add("noise", xywh=[0, 60, 160, 30], color=weed, density=0.25, seed=73)
    s.add("noise", xywh=[0, 60, 160, 30], color=weed_lt, density=0.1, seed=74)
    for fx in (5, 35, 65, 95, 125, 155):
        s.add("vline", x=fx, y_range=[46, 84], color=fence)
    s.add("polyline", points=[[5, 52], [35, 55], [65, 53], [95, 56],
                              [125, 54], [155, 56]], color=fence)
    s.add("polyline", points=[[5, 68], [35, 70], [65, 69], [95, 71],
                              [125, 70], [155, 71]], color=fence)
    # One crow on the wire.
    s.add("dot", xy=[80, 54], size=2, color=crow)
    return s


def shell_station():
    s = Scene("shell_station", "The closed Shell station. Pumps wrapped in "
                               "plastic, hand-lettered CLOSED sign, the "
                               "canopy over an empty lot. Generated by "
                               "gen_estuary3_act3_scenes.py.")
    ink = s.c("ink", "#141420")
    sky = s.c("sky", "#c8c0a8")
    sky_hi = s.c("sky_hi", "#dcd6c2")
    canopy = s.c("canopy", "#e8dcc0")
    canopy_dk = s.c("canopy_dk", "#c4b898")
    red = s.c("red", "#8a2820")
    pole = s.c("pole", "#606060")
    wrap = s.c("wrap", "#d0ccc0")
    wrap_dk = s.c("wrap_dk", "#a8a498")
    lot = s.c("lot", "#c8c0a8")
    lot_dk = s.c("lot_dk", "#9a9484")
    dark = s.c("dark", "#403030")
    shell_y = s.c("shell_y", "#d8b048")

    s.add("vgrad", y_range=[0, 58], stops=[sky_hi, sky])
    s.add("noise", xywh=[0, 6, 160, 14], color=sky_hi, density=0.05, seed=81)
    # Road sign out front — the shell mark going pale.
    s.add("vline", x=16, y_range=[26, 62], color=pole)
    s.add("vline", x=17, y_range=[26, 62], color=pole)
    s.add("rect", xywh=[6, 14, 22, 14], color=wrap)
    s.add("disk", xy=[17, 21], r=5, color=shell_y)
    s.add("ring", xy=[17, 21], r=5, color=red)
    s.add("hline", y=14, x_range=[6, 28], color=ink)
    # Canopy with the red fascia stripe, on two poles.
    s.add("rect", xywh=[34, 20, 96, 8], color=canopy)
    s.add("rect", xywh=[34, 26, 96, 2], color=red)
    s.add("hline", y=20, x_range=[34, 130], color=ink)
    s.add("shade", xywh=[34, 28, 96, 30], color=canopy_dk, amount=0.15)  # canopy shadow
    s.add("rect", xywh=[46, 28, 4, 38], color=pole)
    s.add("rect", xywh=[112, 28, 4, 38], color=pole)
    # Two pumps under plastic — wrap folds as polylines.
    for px in (60, 88):
        s.add("rect", xywh=[px, 40, 16, 24], color=wrap)
        s.add("shade", xywh=[px, 40, 16, 24], color=wrap_dk, amount=0.3)
        s.add("polyline", points=[[px + 2, 42], [px + 9, 52], [px + 4, 62]],
              color=wrap_dk)
        s.add("polyline", points=[[px + 13, 41], [px + 8, 50], [px + 12, 60]],
              color=wrap_dk)
        s.add("polyline", points=[[px, 64], [px + 8, 60], [px + 16, 64]],
              color=ink)                                             # taped hem
        s.add("vline", x=px, y_range=[40, 64], color=ink)
        s.add("vline", x=px + 15, y_range=[40, 64], color=ink)
    # CLOSED, hand-lettered, wired to the pole.
    s.add("rect", xywh=[52, 30, 34, 8], color=canopy)
    s.add("text", xy=[55, 32], s="CLOSED", color=red)
    s.add("hline", y=30, x_range=[52, 86], color=ink)
    # The lot: sun-bleached, cracks, one dark oil ghost per island.
    s.add("vgrad", y_range=[66, 90], stops=[lot, lot_dk])
    s.add("noise", xywh=[0, 68, 160, 22], color=lot_dk, density=0.08, seed=82)
    s.add("polyline", points=[[20, 90], [44, 74], [58, 78]], color=lot_dk)
    s.add("polyline", points=[[120, 90], [108, 78], [130, 72]], color=lot_dk)
    s.add("shade", xywh=[56, 66, 24, 6], color=dark, amount=0.25)
    s.add("shade", xywh=[84, 66, 24, 6], color=dark, amount=0.25)
    s.add("rect", xywh=[34, 64, 96, 3], color=lot_dk)                # island curb
    return s


def scenes():
    return [pier(), tide_gate(), aandahl_house(), bookstore(), cabin_road(),
            elementary_school(), kwik_stop_revisit(), mill_office(),
            shell_station()]


# ── The shelf backdrop · Olaf's cabin wall, 2048 ─────────────────

def shelf_backdrop():
    s = Scene("shelf_backdrop", "The cabin wall behind the slowstock shelf. "
                                "Cedar planks, lamp glow from the left, the "
                                "night window at the right with rain on the "
                                "glass. 2048 frame story. Generated by "
                                "gen_estuary3_act3_scenes.py.")
    ink = s.c("ink", "#0c0a08")
    plank = s.c("plank", "#2c2118")
    plank_lt = s.c("plank_lt", "#3a2c1e")
    plank_hi = s.c("plank_hi", "#4a3826")
    glow = s.c("glow", "#6a5230")
    night = s.c("night", "#101822")
    night_hi = s.c("night_hi", "#1c2a3a")
    star = s.c("star", "#c8d0d8")
    frame = s.c("frame", "#241a10")

    s.add("fill", color=plank)
    # Plank courses with grain.
    for py in range(0, 90, 9):
        s.add("hband", y_range=[py, py + 9], color=plank if (py // 9) % 2 == 0 else plank_lt)
        s.add("hline", y=py, x_range=[0, 160], color=ink)
    s.add("noise", xywh=[0, 0, 160, 90], color=plank_hi, density=0.06, seed=91)
    s.add("noise", xywh=[0, 0, 160, 90], color=ink, density=0.04, seed=92)
    # Lamp glow from the left — the reading lamp is out of frame.
    s.add("shade", xywh=[0, 0, 56, 90], color=glow, amount=0.22)
    s.add("shade", xywh=[0, 20, 30, 50], color=glow, amount=0.3)
    # Night window at the right.
    s.add("rect", xywh=[118, 14, 34, 44], color=frame)
    s.add("vgrad", y_range=[16, 56], x_range=[120, 150], stops=[night_hi, night])
    s.add("vline", x=135, y_range=[16, 56], color=frame)
    s.add("hline", y=36, x_range=[120, 150], color=frame)
    s.add("noise", xywh=[120, 16, 30, 40], color=star, density=0.015, seed=93)
    s.add("noise", xywh=[120, 16, 30, 40], color=night_hi, density=0.1, seed=94)
    return s


def main():
    os.makedirs(ACT3_DIR, exist_ok=True)
    os.makedirs(LIB_DIR, exist_ok=True)
    for s in scenes():
        path = os.path.join(ACT3_DIR, s.id + ".json")
        with open(path, "w") as f:
            json.dump(s.doc(), f, indent=1)
            f.write("\n")
        print("wrote %s (%d layers, %d colors)"
              % (path, len(s.layers), len(s.palette)))
    b = shelf_backdrop()
    path = os.path.join(LIB_DIR, b.id + ".json")
    with open(path, "w") as f:
        json.dump(b.doc(), f, indent=1)
        f.write("\n")
    print("wrote %s (%d layers, %d colors)" % (path, len(b.layers), len(b.palette)))


if __name__ == "__main__":
    main()
