#!/usr/bin/env python3
"""Generate the three Kwik Stop room HeroImage backgrounds.

Deterministic (no RNG) — run it twice, get byte-identical output.
All three lighting variants share one geometry table so the
KwikStopRoom.gd interactable hotspots stay aligned across nights:

    backroom door   art rect x  3-11, y 29-51  (hotspot [36, 205])
    cooler          art rect x 12-33, y 26-52  (hotspot [115, 200])
    radio           art rect x 84-98, y 18-26  (hotspot [420, 90])
    register        art rect x 78-92, y 60-76  (hotspot [425, 345])
    phone           art rect x141-151, y 22-42 (hotspot [730, 130])
    counter         art rect x 40-130, y 62-82

Canvas 160x90, rendered at 800x460 (x*5, y*5.11) by KwikStopRoom.

Uses the 2026-07-10 HeroImage ops: vgrad/hgrad (Bayer-dithered
gradients), disk/ring, noise (hash speckle), shade (partial
coverage), checker.
"""
import json
import os

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "..",
                       "resources", "games", "vol7", "estuary_3",
                       "sprites", "act1")

# Palette slots (same meaning across variants):
#  0 ink   1 wall   2 wall_lit   3 wood   4 wood_lt   5 tan
#  6 cream 7 floor  8 floor_dk   9 steel 10 steel_lt 11 night_deep
# 12 night 13 red  14 cool_blue 15 white
VARIANTS = {
    "kwik_stop_room": {
        "palette": ["#0a0d10", "#3a4a3e", "#4a5c4c", "#6a5238",
                    "#8a6c48", "#c8b878", "#e8dc90", "#4a4434",
                    "#2e2a20", "#5a6268", "#848c92", "#0c1218",
                    "#24324a", "#b04038", "#4878a0", "#ece8dc"],
        "glow_a": 0.30, "glow_b": 0.30, "pool": 0.12,
        "moth": True, "star": False,
        "notes": ("Behind the counter at 2:14 AM. Fluorescent above the "
                  "register buzzes; the one over aisle 3 flickers. Backroom "
                  "door left of frame, up two steps. Cooler glows cold blue. "
                  "Window at right shows the fog-lit lot and the moth at the "
                  "glass. Sixteen-color palette, 160x90, generated by "
                  "tools/sprites/gen_kwik_stop_rooms.py."),
    },
    "kwik_stop_room_late": {
        "palette": ["#08090c", "#2e3a30", "#3a4a40", "#5a4432",
                    "#74583c", "#a89058", "#c8b070", "#3c3828",
                    "#242018", "#4a5258", "#6c747a", "#0a0e14",
                    "#1c2638", "#8c3830", "#3c6488", "#c8c4b8"],
        "glow_a": 0.15, "glow_b": 0.15, "pool": 0.06,
        "moth": True, "star": False,
        "notes": ("Same room, late-shift dim (turn 8+). Fluorescents a "
                  "shade down, wall cooler, floor darker, the window lot "
                  "nearly black. Generated by gen_kwik_stop_rooms.py."),
    },
    "kwik_stop_room_night_12_still": {
        "palette": ["#0a0e10", "#3e4a3c", "#52604e", "#785a3e",
                    "#987450", "#d0bc80", "#f0e498", "#524c3a",
                    "#363024", "#626a70", "#8c949a", "#0e141c",
                    "#2a3a54", "#b84440", "#5484ac", "#f4f0e4"],
        "glow_a": 0.35, "glow_b": 0.35, "pool": 0.16,
        "moth": False, "star": True,
        "notes": ("Night 12, Labor Day eve. Unusually still — the aisle-3 "
                  "fluorescent does not flicker, the moth is gone, one "
                  "clear star over the lot. Slightly brighter and cleaner "
                  "than any other night. Generated by "
                  "gen_kwik_stop_rooms.py."),
    },
}

INK, WALL, WALL_LIT, WOOD, WOOD_LT, TAN, CREAM, FLOOR, FLOOR_DK, \
    STEEL, STEEL_LT, NIGHT_DEEP, NIGHT, RED, BLUE, WHITE = range(16)


def build_layers(v):
    L = []
    # ── Wall + ceiling ───────────────────────────────────────────
    L.append({"op": "vgrad", "y_range": [0, 58], "stops": [WALL_LIT, WALL]})
    L.append({"op": "hband", "y_range": [0, 3], "color": INK})
    L.append({"op": "hline", "y": 3, "x_range": [0, 160], "color": INK})
    # Fluorescent tubes (A over the register, B over aisle 3) + glow.
    L.append({"op": "rect", "xywh": [34, 1, 28, 2], "color": WHITE})
    L.append({"op": "shade", "xywh": [28, 3, 40, 4], "color": CREAM,
              "amount": v["glow_a"]})
    L.append({"op": "rect", "xywh": [98, 1, 24, 2], "color": WHITE})
    L.append({"op": "shade", "xywh": [93, 3, 34, 4], "color": CREAM,
              "amount": v["glow_b"]})
    # Faint wall scuff, low on the wall where scuffs live.
    L.append({"op": "noise", "xywh": [0, 44, 160, 14], "color": WALL_LIT,
              "density": 0.02, "seed": 3})

    # ── High display shelves with product clutter ────────────────
    for sx in (10, 96):
        prods = [RED, BLUE, CREAM, TAN, RED, TAN, BLUE, CREAM, TAN, RED]
        for i, c in enumerate(prods):
            px = sx + 2 + i * 4
            ph = 4 + (i * 7 + sx) % 3          # varied heights, deterministic
            L.append({"op": "rect", "xywh": [px, 10 - ph, 3, ph], "color": c})
        L.append({"op": "rect", "xywh": [sx, 10, 44, 2], "color": TAN})
        L.append({"op": "hline", "y": 12, "x_range": [sx, sx + 44],
                  "color": INK})

    # ── Wall clock (02:14, every night) ──────────────────────────
    L.append({"op": "rect", "xywh": [58, 16, 23, 9], "color": WHITE})
    L.append({"op": "hline", "y": 16, "x_range": [58, 81], "color": INK})
    L.append({"op": "hline", "y": 24, "x_range": [58, 81], "color": INK})
    L.append({"op": "vline", "x": 58, "y_range": [16, 25], "color": INK})
    L.append({"op": "vline", "x": 80, "y_range": [16, 25], "color": INK})
    L.append({"op": "text", "xy": [60, 18], "s": "02-14", "color": INK})

    # ── Ledge above the counter + the silver radio on it ─────────
    L.append({"op": "hband", "y_range": [26, 28], "color": TAN})
    L.append({"op": "hline", "y": 28, "x_range": [0, 120], "color": INK})
    L.append({"op": "rect", "xywh": [84, 18, 14, 8], "color": STEEL_LT})
    for gy in (20, 22, 24):
        L.append({"op": "hline", "y": gy, "x_range": [85, 92], "color": INK})
    L.append({"op": "dot", "xy": [95, 20], "size": 1, "color": INK})
    L.append({"op": "dot", "xy": [95, 23], "size": 1, "color": INK})
    L.append({"op": "polyline", "points": [[97, 18], [101, 12]],
              "color": STEEL_LT})

    # ── Backroom door (up two steps, left of frame) ──────────────
    L.append({"op": "rect", "xywh": [3, 29, 8, 22], "color": STEEL})
    L.append({"op": "rect", "xywh": [4, 31, 6, 7], "color": STEEL_LT})
    L.append({"op": "vline", "x": 2, "y_range": [28, 52], "color": INK})
    L.append({"op": "vline", "x": 11, "y_range": [28, 52], "color": INK})
    L.append({"op": "hline", "y": 28, "x_range": [2, 12], "color": INK})
    L.append({"op": "dot", "xy": [9, 41], "size": 1, "color": INK})   # deadbolt
    L.append({"op": "rect", "xywh": [2, 51, 10, 2], "color": TAN})    # step 1
    L.append({"op": "rect", "xywh": [1, 53, 12, 2], "color": WOOD})   # step 2
    L.append({"op": "hline", "y": 51, "x_range": [1, 13], "color": INK})

    # ── Cooler (glowing cold interior) ───────────────────────────
    L.append({"op": "rect", "xywh": [12, 26, 22, 26], "color": STEEL_LT})
    L.append({"op": "rect", "xywh": [12, 26, 22, 3], "color": RED})   # brand
    L.append({"op": "rect", "xywh": [14, 30, 17, 20], "color": BLUE})
    L.append({"op": "hline", "y": 36, "x_range": [14, 31], "color": WHITE})
    L.append({"op": "hline", "y": 43, "x_range": [14, 31], "color": WHITE})
    for i in range(5):                                # sodas · top shelf
        L.append({"op": "rect", "xywh": [15 + i * 3, 32, 2, 4],
                  "color": RED if i % 2 == 0 else CREAM})
    for i in range(5):                                # OJ · middle shelf
        L.append({"op": "rect", "xywh": [15 + i * 3, 38, 2, 5],
                  "color": CREAM if i % 2 == 0 else TAN})
    for i in range(4):                                # milk · bottom shelf
        L.append({"op": "rect", "xywh": [16 + i * 4, 45, 3, 5],
                  "color": WHITE})
    L.append({"op": "vline", "x": 32, "y_range": [30, 48], "color": WHITE})
    L.append({"op": "hline", "y": 26, "x_range": [12, 34], "color": INK})
    L.append({"op": "hline", "y": 52, "x_range": [12, 34], "color": INK})
    L.append({"op": "vline", "x": 12, "y_range": [26, 52], "color": INK})
    L.append({"op": "vline", "x": 33, "y_range": [26, 52], "color": INK})

    # ── Window at right · the lot at 2 AM ────────────────────────
    L.append({"op": "rect", "xywh": [120, 30, 18, 28], "color": INK})
    L.append({"op": "vgrad", "y_range": [31, 57], "x_range": [121, 137],
              "stops": [NIGHT, NIGHT_DEEP]})
    L.append({"op": "hline", "y": 50, "x_range": [121, 137],
              "color": NIGHT_DEEP})                    # lot horizon
    L.append({"op": "dot", "xy": [126, 46], "size": 2, "color": CREAM})  # pump light
    L.append({"op": "shade", "xywh": [124, 44, 6, 5], "color": CREAM,
              "amount": 0.2})
    if v["moth"]:
        L.append({"op": "dot", "xy": [133, 36], "size": 1, "color": CREAM})
    if v["star"]:
        L.append({"op": "dot", "xy": [131, 33], "size": 1, "color": WHITE})
    L.append({"op": "vline", "x": 129, "y_range": [31, 57], "color": INK})
    L.append({"op": "hline", "y": 44, "x_range": [121, 137], "color": INK})

    # ── Corner booth by the window ───────────────────────────────
    L.append({"op": "rect", "xywh": [150, 44, 9, 14], "color": RED})
    L.append({"op": "hline", "y": 44, "x_range": [150, 159], "color": INK})
    L.append({"op": "rect", "xywh": [140, 50, 9, 2], "color": WOOD_LT})
    L.append({"op": "vline", "x": 144, "y_range": [52, 58], "color": INK})

    # ── Payphone on the right wall ───────────────────────────────
    L.append({"op": "rect", "xywh": [143, 22, 7, 11], "color": STEEL})
    L.append({"op": "rect", "xywh": [141, 22, 2, 9], "color": INK})   # handset
    L.append({"op": "dot", "xy": [147, 25], "size": 1, "color": CREAM})
    L.append({"op": "polyline", "points": [[142, 31], [140, 35], [143, 39]],
              "color": INK})                           # stretched cord

    # ── Floor ────────────────────────────────────────────────────
    L.append({"op": "hband", "y_range": [58, 60], "color": TAN})     # baseboard
    L.append({"op": "hline", "y": 58, "x_range": [0, 160], "color": INK})
    L.append({"op": "vgrad", "y_range": [60, 90], "stops": [FLOOR, FLOOR_DK]})
    L.append({"op": "checker", "xywh": [0, 62, 160, 28],
              "colors": [FLOOR, FLOOR_DK], "cell": 6})
    L.append({"op": "shade", "xywh": [0, 78, 160, 12], "color": FLOOR_DK,
              "amount": 0.5})
    L.append({"op": "noise", "xywh": [0, 62, 160, 28], "color": FLOOR_DK,
              "density": 0.05, "seed": 11})
    L.append({"op": "shade", "xywh": [12, 60, 24, 5], "color": BLUE,
              "amount": 0.25})                         # cooler glow spill
    L.append({"op": "shade", "xywh": [44, 60, 76, 6], "color": CREAM,
              "amount": v["pool"]})                    # fluorescent pool

    # ── Counter (register, tape roll, tip jar) ───────────────────
    L.append({"op": "rect", "xywh": [98, 57, 5, 5], "color": CREAM})  # tip jar
    L.append({"op": "dot", "xy": [100, 60], "size": 1, "color": RED})
    L.append({"op": "rect", "xywh": [40, 62, 90, 20], "color": WOOD})
    L.append({"op": "rect", "xywh": [40, 62, 90, 3], "color": WOOD_LT})
    L.append({"op": "hline", "y": 62, "x_range": [40, 130], "color": INK})
    L.append({"op": "noise", "xywh": [40, 66, 90, 16], "color": WOOD_LT,
              "density": 0.04, "seed": 23})            # wood grain
    for px in (58, 76, 94, 112):
        L.append({"op": "vline", "x": px, "y_range": [66, 82], "color": INK})
    L.append({"op": "vline", "x": 40, "y_range": [62, 82], "color": INK})
    L.append({"op": "vline", "x": 129, "y_range": [62, 82], "color": INK})
    # Register: steel body, cool display, keypad, paper tape.
    L.append({"op": "rect", "xywh": [81, 56, 4, 5], "color": WHITE})  # tape
    L.append({"op": "rect", "xywh": [78, 60, 14, 12], "color": STEEL_LT})
    L.append({"op": "rect", "xywh": [79, 61, 12, 3], "color": BLUE})
    for ky in (66, 68, 70):
        for kx in (80, 83, 86, 89):
            L.append({"op": "dot", "xy": [kx, ky], "size": 1, "color": INK})
    L.append({"op": "hline", "y": 60, "x_range": [78, 92], "color": INK})
    L.append({"op": "vline", "x": 78, "y_range": [60, 72], "color": INK})
    L.append({"op": "vline", "x": 91, "y_range": [60, 72], "color": INK})

    # ── The broom, leaning against the counter's right end ───────
    L.append({"op": "polyline", "points": [[124, 60], [128, 84]],
              "color": WOOD_LT})
    L.append({"op": "rect", "xywh": [126, 84, 5, 4], "color": TAN})
    L.append({"op": "hline", "y": 84, "x_range": [126, 131], "color": INK})

    return L


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    for name, v in VARIANTS.items():
        doc = {
            "id": name,
            "notes": v["notes"],
            "w": 160, "h": 90,
            "palette": v["palette"],
            "layers": build_layers(v),
        }
        path = os.path.join(OUT_DIR, name + ".json")
        with open(path, "w") as f:
            json.dump(doc, f, indent=1)
            f.write("\n")
        print("wrote %s (%d layers)" % (path, len(doc["layers"])))


if __name__ == "__main__":
    main()
