#!/usr/bin/env python3
"""Generate Community Planned region-banner HeroImages.

Deterministic — byte-identical output on every run. One 160x36
banner per region, drawn in each region's mood:

  graustark      home soil · old-town rooflines at dusk, the
                 riverboat memory on the water
  harmony_creek  engineered community · identical gables in a row
                 under a too-clean sky
  small_wood     the front · night treeline with THE TOWER — four
                 variants keyed to tower brightness (dim / warming /
                 bright / white); the engine swaps the banner as the
                 brightness changes.

Output: godot/resources/games/community_planned/banners/<id>.json
Rendered by HeroImage into the region folder panels.
"""
import json
import os

W, H = 160, 36
OUT = os.path.join(os.path.dirname(__file__), "..", "..",
                   "resources", "games", "community_planned", "banners")


class Scene:
    def __init__(self, sid, notes):
        self.id = sid
        self.notes = notes
        self.palette = []
        self._idx = {}
        self.layers = []

    def c(self, name, hexv=None):
        if name not in self._idx:
            if hexv is None:
                raise KeyError(name)
            self._idx[name] = len(self.palette)
            self.palette.append(hexv)
        return self._idx[name]

    def add(self, op, **kw):
        d = {"op": op}
        d.update(kw)
        self.layers.append(d)

    def doc(self):
        return {"id": self.id, "notes": self.notes, "w": W, "h": H,
                "palette": self.palette, "layers": self.layers}


def spruce(s, x, base_y, height, color):
    half = max(2, height // 3)
    s.add("poly", points=[[x, base_y - height], [x - half, base_y - height // 3],
                          [x + half, base_y - height // 3]], color=color)
    s.add("poly", points=[[x, base_y - (height * 3) // 4],
                          [x - half - 1, base_y], [x + half + 1, base_y]],
          color=color)


def graustark():
    s = Scene("graustark", "Home soil. Old-town rooflines at dusk; the "
                           "riverboat memory on the water. Generated by "
                           "gen_cp_region_banners.py.")
    ink = s.c("ink", "#100c12")
    sky_hi = s.c("sky_hi", "#c88a58")
    sky = s.c("sky", "#8a5468")
    sky_dk = s.c("sky_dk", "#4a3458")
    town = s.c("town", "#241a28")
    win = s.c("win", "#e8c878")
    water = s.c("water", "#2a2438")
    water_lt = s.c("water_lt", "#4a3e58")
    boat = s.c("boat", "#362a44")
    boat_lt = s.c("boat_lt", "#c8a868")

    s.add("vgrad", y_range=[0, 24], stops=[sky_dk, sky, sky_hi])
    # Old-town silhouette — varied rooflines, a church spire.
    s.add("rect", xywh=[0, 16, 26, 12], color=town)
    s.add("poly", points=[[10, 8], [13, 16], [7, 16]], color=town)   # spire
    s.add("vline", x=10, y_range=[5, 8], color=town)
    s.add("rect", xywh=[28, 13, 18, 15], color=town)
    s.add("poly", points=[[28, 13], [37, 8], [46, 13]], color=town)
    s.add("rect", xywh=[48, 17, 14, 11], color=town)
    s.add("rect", xywh=[64, 12, 20, 16], color=town)
    s.add("poly", points=[[64, 12], [74, 7], [84, 12]], color=town)
    s.add("rect", xywh=[86, 15, 12, 13], color=town)
    s.add("rect", xywh=[100, 18, 16, 10], color=town)
    # Lit windows, sparse.
    for wx, wy in ((4, 20), (18, 22), (33, 17), (52, 21), (70, 16),
                   (76, 20), (90, 19), (105, 22)):
        s.add("dot", xy=[wx, wy], size=1, color=win)
    # The water.
    s.add("vgrad", y_range=[28, 36], stops=[water_lt, water])
    s.add("noise", xywh=[0, 29, 160, 7], color=water_lt, density=0.08, seed=3)
    s.add("hline", y=28, x_range=[0, 160], color=ink)
    # The riverboat — the canonical memory, moored at the right.
    s.add("rect", xywh=[122, 22, 30, 6], color=boat)
    s.add("rect", xywh=[128, 17, 16, 5], color=boat)
    s.add("rect", xywh=[133, 13, 6, 4], color=boat)
    s.add("hline", y=22, x_range=[122, 152], color=boat_lt)
    s.add("hline", y=17, x_range=[128, 144], color=boat_lt)
    s.add("vline", x=136, y_range=[9, 13], color=boat)      # stack
    s.add("dot", xy=[131, 19], size=1, color=win)
    s.add("dot", xy=[139, 19], size=1, color=win)
    s.add("dot", xy=[127, 25], size=1, color=win)
    s.add("dot", xy=[145, 25], size=1, color=win)
    # Reflection.
    s.add("shade", xywh=[124, 29, 26, 4], color=boat_lt, amount=0.15)
    return s


def harmony_creek():
    s = Scene("harmony_creek", "Engineered community. Identical gables in "
                               "a row under a too-clean sky; lawns the same "
                               "green on purpose. Generated by "
                               "gen_cp_region_banners.py.")
    ink = s.c("ink", "#101410")
    sky = s.c("sky", "#a8c8d8")
    sky_hi = s.c("sky_hi", "#d0e4ec")
    cloud = s.c("cloud", "#eef4f6")
    house = s.c("house", "#c8b8a0")
    roof = s.c("roof", "#7a5a48")
    door = s.c("door", "#4a3828")
    lawn = s.c("lawn", "#4a8a3a")
    lawn_lt = s.c("lawn_lt", "#5aa044")
    walk = s.c("walk", "#b8b4a8")

    s.add("vgrad", y_range=[0, 26], stops=[sky_hi, sky])
    s.add("rect", xywh=[18, 4, 14, 3], color=cloud)
    s.add("rect", xywh=[22, 3, 7, 2], color=cloud)
    s.add("rect", xywh=[112, 6, 12, 2], color=cloud)
    # Seven identical houses. The repetition IS the region.
    for i in range(7):
        x = 4 + i * 22
        s.add("rect", xywh=[x, 16, 16, 10], color=house)
        s.add("poly", points=[[x - 1, 16], [x + 8, 10], [x + 17, 16]], color=roof)
        s.add("rect", xywh=[x + 6, 20, 4, 6], color=door)
        s.add("dot", xy=[x + 3, 19], size=1, color=ink)
        s.add("dot", xy=[x + 13, 19], size=1, color=ink)
    # Lawns + the one shared sidewalk line.
    s.add("vgrad", y_range=[26, 36], stops=[lawn_lt, lawn])
    s.add("noise", xywh=[0, 27, 160, 9], color=lawn, density=0.12, seed=7)
    s.add("hband", y_range=[30, 32], color=walk)
    s.add("hline", y=30, x_range=[0, 160], color=ink)
    for jx in range(8, 160, 22):
        s.add("vline", x=jx, y_range=[30, 32], color=ink)
    return s


def small_wood(variant, window_hex, glow_amt, sky_lift):
    s = Scene("small_wood_" + variant,
              "The front. Night treeline; the tower above the wood — "
              "brightness '%s'. The engine swaps banner variants as the "
              "tower changes. Generated by gen_cp_region_banners.py." % variant)
    ink = s.c("ink", "#0a0c10")
    sky = s.c("sky", "#1a2230" if sky_lift == 0 else "#242e40")
    sky_hi = s.c("sky_hi", "#2a3648" if sky_lift == 0 else "#3a4a60")
    forest = s.c("forest", "#0e1610")
    forest_lt = s.c("forest_lt", "#16221a")
    tower = s.c("tower", "#1e1a24")
    tower_lt = s.c("tower_lt", "#38304a")
    win = s.c("win", window_hex)
    star = s.c("star", "#b8c4d0")

    s.add("vgrad", y_range=[0, 30], stops=[sky_hi, sky])
    s.add("noise", xywh=[0, 0, 160, 14], color=star, density=0.012, seed=9)
    # Treeline — two depths.
    for x in range(4, 100, 11):
        spruce(s, x, 34, 14 + (x * 3) % 5, forest_lt)
    for x in range(9, 104, 13):
        spruce(s, x, 36, 18 + (x * 5) % 6, forest)
    s.add("hband", y_range=[34, 36], color=forest)
    # The tower, above the wood at the right.
    s.add("rect", xywh=[124, 8, 10, 28], color=tower)
    s.add("vline", x=124, y_range=[8, 36], color=ink)
    s.add("vline", x=133, y_range=[8, 36], color=ink)
    s.add("vline", x=126, y_range=[8, 36], color=tower_lt)
    s.add("poly", points=[[122, 8], [129, 3], [136, 8]], color=tower)
    # The window — the only legible reading of what Dean is doing.
    s.add("rect", xywh=[127, 14, 4, 5], color=win)
    if glow_amt > 0.0:
        s.add("shade", xywh=[121, 10, 16, 13], color=win, amount=glow_amt)
        s.add("shade", xywh=[116, 6, 26, 21], color=win, amount=glow_amt * 0.4)
    # Near trees crowd the tower base.
    spruce(s, 114, 36, 16, forest)
    spruce(s, 144, 36, 14, forest)
    return s


def county_seat():
    s = Scene("county_seat", "The courthouse at dusk. Limestone, columns, "
                             "one office lit late — somebody's associate is "
                             "still reading. Generated by "
                             "gen_cp_region_banners.py.")
    ink = s.c("ink", "#0e0e14")
    sky = s.c("sky", "#3a3e52")
    sky_lo = s.c("sky_lo", "#6a5468")
    stone = s.c("stone", "#a89878")
    stone_dk = s.c("stone_dk", "#786a52")
    stone_sh = s.c("stone_sh", "#544a3a")
    win_dark = s.c("win_dark", "#2a2836")
    win_lit = s.c("win_lit", "#e8c878")
    lawn = s.c("lawn", "#26301e")
    lamp = s.c("lamp", "#c8b878")

    # Dusk sky, heavier at the top · government-building weather.
    s.add("vgrad", y_range=[0, 26], stops=[ink, sky, sky_lo])
    # Lawn strip + walk.
    s.add("rect", xywh=[0, 28, 160, 8], color=lawn)
    s.add("hband", y_range=[27, 28], color=stone_sh)
    # The courthouse block · centered mass with side wings.
    s.add("rect", xywh=[30, 12, 100, 16], color=stone_dk)      # wings
    s.add("rect", xywh=[56, 8, 48, 20], color=stone)           # center
    # Pediment + steps.
    s.add("poly", points=[[56, 8], [80, 2], [104, 8]], color=stone)
    s.add("poly", points=[[60, 8], [80, 4], [100, 8]], color=stone_dk)
    s.add("rect", xywh=[66, 26, 28, 2], color=stone_dk)        # steps
    # Four columns.
    for cx in (62, 71, 88, 97):
        s.add("rect", xywh=[cx, 10, 3, 16], color=stone)
        s.add("vline", x=cx, y_range=[10, 26], color=stone_sh)
    # Door between the middle columns.
    s.add("rect", xywh=[77, 18, 6, 8], color=win_dark)
    # Wing windows · two rows, dark · one lit on the right wing:
    # the office that stays late.
    for wx in (34, 41, 48, 108, 115, 122):
        s.add("rect", xywh=[wx, 15, 4, 5], color=win_dark)
        s.add("rect", xywh=[wx, 22, 4, 4], color=win_dark)
    s.add("rect", xywh=[115, 15, 4, 5], color=win_lit)
    s.add("shade", xywh=[111, 12, 12, 11], color=win_lit, amount=0.18)
    # Flag pole off the pediment peak.
    s.add("vline", x=80, y_range=[0, 2], color=stone_sh)
    # Two street lamps on the lawn, small and civic.
    for lx in (12, 148):
        s.add("vline", x=lx, y_range=[20, 28], color=stone_sh)
        s.add("dot", xy=[lx, 19], color=lamp)
        s.add("shade", xywh=[lx - 3, 16, 7, 7], color=lamp, amount=0.22)
    return s


def main():
    os.makedirs(OUT, exist_ok=True)
    scenes = [
        graustark(),
        harmony_creek(),
        county_seat(),
        small_wood("dim",     "#2a2e38", 0.0,  0),
        small_wood("warming", "#8a6428", 0.12, 0),
        small_wood("bright",  "#e8c050", 0.25, 0),
        small_wood("white",   "#f4f2e8", 0.4,  1),
    ]
    for s in scenes:
        path = os.path.join(OUT, s.id + ".json")
        with open(path, "w") as f:
            json.dump(s.doc(), f, indent=1)
            f.write("\n")
        print("wrote %s (%d layers)" % (path, len(s.layers)))


if __name__ == "__main__":
    main()
