#!/usr/bin/env python3
"""Full-scene backdrops for Fey Faire's midway and Earthman
Chronicles' Talikan hub — the two most-inhabited screens of each
stick, previously flat color fills.

Deterministic. Each is authored in its studio's culture (aesthetic
bible): the faire in Rocha's inked-cel dusk mauves; Kyrindi in
Astro-Cortex's cool instrument light. Both are drawn DARK enough to
sit behind UI panels (and are further dimmed at the call site).

Output:
  godot/resources/games/vol7/fey_faire/hero_images/midway_backdrop.json
  godot/resources/games/vol7/earthman_chronicles/hero_images/talikan_backdrop.json
"""
import json
import os

W, H = 160, 90
ROOT = os.path.join(os.path.dirname(__file__), "..", "..",
                    "resources", "games", "vol7")


class Scene:
    def __init__(self, sid, notes):
        self.id = sid
        self.notes = notes
        self.palette = []
        self._idx = {}
        self.layers = []

    def c(self, name, hexv=None):
        if name not in self._idx:
            if hexv is None:
                raise KeyError(name)
            self._idx[name] = len(self.palette)
            self.palette.append(hexv)
        return self._idx[name]

    def add(self, op, **kw):
        d = {"op": op}
        d.update(kw)
        self.layers.append(d)

    def doc(self):
        return {"id": self.id, "notes": self.notes, "w": W, "h": H,
                "palette": self.palette, "layers": self.layers}


def midway_backdrop():
    s = Scene("midway_backdrop",
              "The faire's midway at dusk — big top, tent row, string "
              "lights, the wheel. Rocha inked-cel mauves; drawn dark so "
              "the booth graph reads on top. Generated by "
              "gen_ff_em_backdrops.py.")
    ink = s.c("ink", "#160f18")
    sky_dk = s.c("sky_dk", "#2a1c30")
    sky = s.c("sky", "#42284a")
    horizon = s.c("horizon", "#6a3e58")
    tent = s.c("tent", "#241626")
    tent_lt = s.c("tent_lt", "#3a2440")
    stripe = s.c("stripe", "#4e2c50")
    light = s.c("light", "#e8c88a")
    pennant = s.c("pennant", "#a85878")
    ground = s.c("ground", "#1c1220")
    ground_lt = s.c("ground_lt", "#2a1a2e")

    s.add("vgrad", y_range=[0, 62], stops=[sky_dk, sky, horizon])
    s.add("noise", xywh=[0, 0, 160, 30], color=sky, density=0.05, seed=5)
    # The wheel, far right — ring + spokes + a few lit cars.
    s.add("ring", xy=[132, 34], r=20, color=tent_lt)
    s.add("ring", xy=[132, 34], r=19, color=tent_lt)
    for p in ([132, 14], [152, 34], [132, 54], [112, 34],
              [146, 20], [146, 48], [118, 20], [118, 48]):
        s.add("polyline", points=[[132, 34], p], color=tent_lt)
        s.add("dot", xy=p, size=1, color=light)
    s.add("vline", x=126, y_range=[54, 66], color=tent_lt)
    s.add("vline", x=138, y_range=[54, 66], color=tent_lt)
    # The big top, center-left — striped canvas, pennant on the mast.
    s.add("poly", points=[[18, 62], [52, 24], [86, 62]], color=tent)
    for i in range(5):
        x0 = 26 + i * 11
        s.add("polyline", points=[[52, 26], [x0, 62]], color=stripe)
    s.add("vline", x=52, y_range=[16, 24], color=ink)
    s.add("poly", points=[[52, 16], [62, 19], [52, 22]], color=pennant)
    # Tent row, small, to the left.
    for tx in (2, 96):
        s.add("poly", points=[[tx, 62], [tx + 8, 48], [tx + 16, 62]], color=tent_lt)
        s.add("dot", xy=[tx + 8, 50], size=1, color=pennant)
    # String lights: two sagging lines with lit bulbs.
    s.add("polyline", points=[[0, 20], [40, 28], [80, 22], [120, 30], [159, 24]],
          color=tent_lt)
    for bx, by in ((10, 22), (26, 26), (40, 28), (56, 25), (70, 23),
                   (94, 25), (110, 29), (130, 28), (148, 25)):
        s.add("dot", xy=[bx, by], size=1, color=light)
    s.add("polyline", points=[[0, 40], [50, 46], [100, 40], [159, 46]],
          color=tent_lt)
    for bx2, by2 in ((14, 42), (34, 45), (50, 46), (68, 44), (86, 41),
                     (116, 42), (140, 44)):
        s.add("dot", xy=[bx2, by2], size=1, color=light)
    # Trodden ground.
    s.add("vgrad", y_range=[62, 90], stops=[ground_lt, ground])
    s.add("noise", xywh=[0, 64, 160, 26], color=ground_lt, density=0.10, seed=9)
    s.add("hline", y=62, x_range=[0, 160], color=ink)
    # Lantern pools on the path.
    s.add("shade", xywh=[30, 63, 30, 6], color=light, amount=0.08)
    s.add("shade", xywh=[100, 63, 26, 6], color=light, amount=0.08)
    return s, os.path.join(ROOT, "fey_faire", "hero_images")


def talikan_backdrop():
    s = Scene("talikan_backdrop",
              "Kyrindi Talikan under two moons — spire skyline, the "
              "canal, dust. Astro-Cortex instrument light; drawn dark "
              "so the hub UI reads on top. Generated by "
              "gen_ff_em_backdrops.py.")
    ink = s.c("ink", "#0c0e12")
    sky_dk = s.c("sky_dk", "#141a22")
    sky = s.c("sky", "#22303c")
    dust = s.c("dust", "#3a3630")
    moon_a = s.c("moon_a", "#c8ccd0")
    moon_b = s.c("moon_b", "#8a9298")
    spire = s.c("spire", "#1a2230")
    spire_lt = s.c("spire_lt", "#2e4052")
    glow = s.c("glow", "#7ab0c0")
    canal = s.c("canal", "#16222c")
    canal_lt = s.c("canal_lt", "#2a4250")

    s.add("vgrad", y_range=[0, 58], stops=[sky_dk, sky, dust])
    s.add("noise", xywh=[0, 0, 160, 24], color=moon_b, density=0.010, seed=3)
    # Two moons — the larger low, the small one high and fast.
    s.add("disk", xy=[38, 20], r=7, color=moon_a)
    s.add("disk", xy=[35, 18], r=6, color=sky_dk)          # crescent bite
    s.add("disk", xy=[118, 10], r=3, color=moon_b)
    # Spire skyline — thin verticals with instrument lights.
    for sx, sh in ((12, 26), (30, 34), (52, 22), (70, 40), (92, 28),
                   (112, 36), (134, 24), (150, 30)):
        s.add("rect", xywh=[sx, 58 - sh, 5, sh], color=spire)
        s.add("vline", x=sx + 1, y_range=[58 - sh, 58], color=spire_lt)
        s.add("dot", xy=[sx + 2, 58 - sh + 2], size=1, color=glow)
        if sh > 30:
            s.add("dot", xy=[sx + 2, 58 - sh + 10], size=1, color=glow)
    # Bridges between the tall pair.
    s.add("hline", y=34, x_range=[70, 112], color=spire_lt)
    s.add("hline", y=44, x_range=[30, 70], color=spire_lt)
    # The canal — still water, instrument reflections.
    s.add("hline", y=58, x_range=[0, 160], color=ink)
    s.add("vgrad", y_range=[58, 76], stops=[canal_lt, canal])
    s.add("noise", xywh=[0, 60, 160, 14], color=canal_lt, density=0.06, seed=7)
    for rx in (32, 72, 114):
        s.add("vline", x=rx, y_range=[60, 66], color=glow)
    # Dust plain below the embankment.
    s.add("hline", y=76, x_range=[0, 160], color=ink)
    s.add("vgrad", y_range=[76, 90], stops=[dust, sky_dk])
    s.add("noise", xywh=[0, 77, 160, 13], color=dust, density=0.12, seed=11)
    return s, os.path.join(ROOT, "earthman_chronicles", "hero_images")


def main():
    for builder in (midway_backdrop, talikan_backdrop):
        s, out_dir = builder()
        os.makedirs(out_dir, exist_ok=True)
        path = os.path.join(out_dir, s.id + ".json")
        with open(path, "w") as f:
            json.dump(s.doc(), f, indent=1)
            f.write("\n")
        print("wrote %s (%d layers)" % (path, len(s.layers)))


if __name__ == "__main__":
    main()
