#!/usr/bin/env python3
"""music_direction.py — the MUSIC DIRECTOR's data: resources/music/direction.json

The visual novels' music is directed the way their scenes are: one JSON file is the
single source of truth, scripts/vn/MusicDirector.gd reads it at runtime, and this
tool keeps it honest.

    python3 godot/tools/music_direction.py suggest    # rebuild the *_auto sections from the
                                                       # catalog + scenes (authored sections untouched)
    python3 godot/tools/music_direction.py validate   # CI: every reference resolves
    python3 godot/tools/music_direction.py report     # coverage: which scenes get which music, and why

Sections of direction.json
  defaults        tuning: base intensity, attack / release seconds, leitmotif cooldown…
  lexicon         words that push intensity up (tension) or down (calm) when the director
                  infers intensity from the writing
  scenes          AUTHORED per-scene cue sheets: {track, intensity, beats:[{at, …}]}
  locales         AUTHORED background → track (bg src, e.g. "3d:diner_interior", per volume)
  characters      AUTHORED character key → {theme, leitmotif: true|false}
  locales_auto    GENERATED by `suggest` — bg srcs matched to same-volume catalog tracks
  characters_auto GENERATED by `suggest` — catalog "chars" tags on *_theme tracks
Authored entries always win over *_auto ones.
"""
import json, os, re, sys, glob, collections

HERE = os.path.dirname(os.path.abspath(__file__))
GODOT = os.path.dirname(HERE)
DIRECTION = os.path.join(GODOT, 'resources', 'music', 'direction.json')
CATALOG = os.path.join(GODOT, 'resources', 'music_catalog.json')
SCENES = os.path.join(GODOT, 'resources', 'scenes')

DEFAULT = {
    "_doc": "MUSIC DIRECTOR data — read by scripts/vn/MusicDirector.gd. Edit the authored sections "
            "(scenes, locales, characters, defaults, lexicon); regenerate *_auto with "
            "`python3 godot/tools/music_direction.py suggest`; CI runs `validate`. "
            "See lore/_MUSIC_DIRECTION_PLAYBOOK.md.",
    "defaults": {
        "_doc": "intensity 0..1 drives layered (stems) tracks: 0 pad+chords · 0.25 +bass · 0.5 +drums · 0.75 +lead. "
                "attack/release are seconds for the smoothed intensity to rise / fall. leitmotif_cooldown_nodes: "
                "nodes before another character's theme may be queued in the same scene.",
        "base_intensity": 0.5,
        "attack_sec": 2.5,
        "release_sec": 8.0,
        "choice_intensity": 0.85,
        "interlude_intensity": 0.2,
        "cg_intensity": 0.9,
        "think_offset": -0.1,
        "word_step": 0.12,
        "leitmotifs": True,
        "leitmotif_cooldown_nodes": 40,
        "end_of_volume_release": True
    },
    "lexicon": {
        "_doc": "lowercase words / phrases scanned in narrate / say / think text (whole-word for single words).",
        "tension": ["blood", "gun", "knife", "run", "running", "scream", "screams", "shout", "shouting", "fire", "burning",
                    "dead", "death", "die", "kill", "killed", "threat", "danger", "afraid", "fear", "panic", "storm",
                    "siren", "sirens", "chase", "fight", "hit", "slam", "slams", "crash", "break", "breaks", "now",
                    "hurry", "wrong", "demon", "devil", "trapped", "locked", "lie", "lying", "liar", "shaking"],
        "calm": ["quiet", "quietly", "soft", "softly", "gentle", "slow", "slowly", "still", "rest", "sleep", "asleep",
                 "breathe", "breath", "warm", "smile", "smiles", "laugh", "laughs", "home", "tea", "coffee", "rain",
                 "morning", "sunday", "safe", "calm", "hum", "hums"]
    },
    "scenes": {
        "_doc": "AUTHORED cue sheets, keyed by scene id: {\"track\": catalog id, \"intensity\": 0..1, \"silence\": bool, "
                "\"beats\": [{\"at\": node index | \"choice\" | \"cg\" | \"interlude\" | \"end\", \"intensity\": 0..1, "
                "\"track\": id, \"stinger\": name, \"silence\": bool, \"fade\": sec}]}. Scene nodes may also carry "
                "{\"t\": \"music\", …} directives with the same keys."
    },
    "locales": {"_doc": "AUTHORED bg src → {\"<vol>\": catalog id} (or a plain id for every volume)."},
    "characters": {"_doc": "AUTHORED character key → {\"theme\": catalog id, \"leitmotif\": bool}. leitmotif false = never auto-queue."},
    "locales_auto": {},
    "characters_auto": {}
}

GENERIC = {'interior', 'exterior', 'the', 'and', 'of', 'bg', 'png', 'jpg', 'assets', 'backgrounds', 'night', 'day',
           'morning', 'evening', 'back', 'room', 'station', 'front', 'side', 'house', 'home', 'main', 'old', 'new',
           'big', 'little', 'small', 'upper', 'lower', 'inside', 'outside', 'area', 'place', 'ambient', 'ambience'}


def load_json(p):
    with open(p, encoding='utf-8') as f:
        return json.load(f)


def scenes():
    out = {}
    for f in glob.glob(os.path.join(SCENES, 'vol*', '*.json')):
        d = load_json(f)
        out[d.get('id') or os.path.splitext(os.path.basename(f))[0]] = d
    return out


def toks(s):
    s = s.split('/')[-1].rsplit('.', 1)[0].replace('3d:', '')
    return [t for t in re.split(r'[^a-z0-9]+', s.lower()) if len(t) > 2 and not t.isdigit() and t not in GENERIC and not re.fullmatch(r'vol\d', t)]


def suggest(direction, cat, sc):
    # backgrounds → the same volume's non-theme tracks sharing a distinctive word
    bgs = collections.Counter()
    for d in sc.values():
        for n in d.get('nodes', []):
            if n.get('t') == 'bg' and isinstance(n.get('src'), str) and n['src']:
                bgs[(int(d.get('vol', 0)), n['src'])] += 1
    loc = {}
    for (vol, src), _ in sorted(bgs.items()):
        tk = toks(src)
        best, score = None, 0
        for c in cat:
            if c.get('vol') != vol or 'theme' in c['id']:
                continue
            words = set(re.split(r'[^a-z0-9]+', c['id'].lower()))
            sc_ = sum(2 if t in words else 0 for t in tk)
            if sc_ > score:
                best, score = c['id'], sc_
        if best:
            loc.setdefault(src, {})[str(vol)] = best
    # characters → their theme track(s) (catalog "chars" on *_theme entries)
    chars = {}
    for c in cat:
        if 'theme' not in c['id']:
            continue
        for ch in c.get('chars') or []:
            if ch.startswith('_'):
                continue
            chars.setdefault(ch, {"theme": c['id'], "leitmotif": True})
    # speakers whose key differs from the catalog tag ("Faust" vs faust3, "Maya" vs maya_kid):
    # alias the speaker to the theme when one key prefixes the other (≥ 4 letters, unambiguous)
    speakers = collections.Counter()
    for d in sc.values():
        for n in d.get('nodes', []):
            if n.get('t') in ('say', 'think') and isinstance(n.get('char'), str):
                speakers[n['char'].strip().lower().replace(' ', '_')] += 1
    for sp in speakers:
        if sp in chars or len(sp) < 4:
            continue
        # prefix only at a word boundary: faust → faust3, maya → maya_kid, frasier_temple → frasier
        # (never carlos → carl)
        hits = [k for k in list(chars) if 'alias_of' not in chars[k] and (
            (k.startswith(sp) and k[len(sp)] in '_0123456789') or (sp.startswith(k + '_') and len(k) >= 4))]
        if len(hits) == 1:
            chars[sp] = dict(chars[hits[0]], alias_of=hits[0])
    direction['locales_auto'] = dict(sorted(loc.items()))
    direction['characters_auto'] = dict(sorted(chars.items()))
    return len(loc), len(chars)


def validate(direction, cat, sc):
    ids = {c['id'] for c in cat}
    errors, warns = [], []
    for k in ('defaults', 'lexicon', 'scenes', 'locales', 'characters', 'locales_auto', 'characters_auto'):
        if k not in direction:
            errors.append(f'missing section "{k}"')
    d = direction.get('defaults', {})
    for k in ('base_intensity', 'choice_intensity', 'interlude_intensity', 'cg_intensity'):
        v = d.get(k)
        if not isinstance(v, (int, float)) or not 0 <= v <= 1:
            errors.append(f'defaults.{k} must be 0..1 (got {v!r})')

    def chk_track(where, t):
        if t is not None and t not in ids:
            errors.append(f'{where}: track "{t}" is not in music_catalog.json')

    def chk_int(where, v):
        if v is not None and (not isinstance(v, (int, float)) or not 0 <= v <= 1):
            errors.append(f'{where}: intensity must be 0..1 (got {v!r})')

    for sid, cue in direction.get('scenes', {}).items():
        if sid.startswith('_'):
            continue
        if sid not in sc:
            errors.append(f'scenes.{sid}: no such scene')
            continue
        chk_track(f'scenes.{sid}', cue.get('track'))
        chk_int(f'scenes.{sid}', cue.get('intensity'))
        n = len(sc[sid].get('nodes', []))
        for i, b in enumerate(cue.get('beats', [])):
            at = b.get('at')
            if isinstance(at, int):
                if not 0 <= at < n:
                    errors.append(f'scenes.{sid}.beats[{i}]: at {at} is outside 0..{n - 1}')
            elif at not in ('choice', 'cg', 'interlude', 'end'):
                errors.append(f'scenes.{sid}.beats[{i}]: at must be a node index or choice / cg / interlude / end')
            chk_track(f'scenes.{sid}.beats[{i}]', b.get('track'))
            chk_int(f'scenes.{sid}.beats[{i}]', b.get('intensity'))
    for sec in ('locales', 'locales_auto'):
        for src, m in direction.get(sec, {}).items():
            if src.startswith('_'):
                continue
            for vol, t in (m.items() if isinstance(m, dict) else [('*', m)]):
                chk_track(f'{sec}.{src}.{vol}', t)
    for sec in ('characters', 'characters_auto'):
        for ch, m in direction.get(sec, {}).items():
            if ch.startswith('_'):
                continue
            chk_track(f'{sec}.{ch}', m.get('theme'))
    # music directives inside the scenes themselves
    for sid, s in sc.items():
        for i, n in enumerate(s.get('nodes', [])):
            if n.get('t') == 'music':
                chk_track(f'{sid}[{i}] music', n.get('track'))
                chk_int(f'{sid}[{i}] music', n.get('intensity'))
            if n.get('t') == 'bgm' and n.get('src') and not any(c['src'] == n['src'] for c in cat):
                warns.append(f'{sid}[{i}] bgm "{n["src"]}" is not a catalog src')
    return errors, warns


def report(direction, cat, sc):
    by_src = {c['src']: c['id'] for c in cat}
    rows = collections.Counter()
    for sid, s in sorted(sc.items()):
        vol = str(s.get('vol', ''))
        nodes = s.get('nodes', [])
        why = None
        if sid in direction['scenes']:
            why = 'authored cue sheet'
        elif any(n.get('t') == 'music' for n in nodes):
            why = 'music directive'
        elif any(n.get('t') == 'bgm' for n in nodes):
            why = 'bgm directive'
        else:
            for n in nodes:
                if n.get('t') == 'bg' and n.get('src'):
                    m = direction['locales'].get(n['src']) or direction['locales_auto'].get(n['src'])
                    if m and (isinstance(m, str) or vol in m):
                        why = 'locale track'
                        break
        if not why:
            if any(sid in (c.get('chapters') or []) for c in cat):
                why = 'chapter tracks (catalog)'
            else:
                why = 'volume queue only'
        rows[why] += 1
    total = sum(rows.values())
    print(f'{total} scenes — where their music comes from:')
    for k, v in rows.most_common():
        print(f'  {v:4d}  {k}')
    print(f'leitmotif characters: {len([k for k in direction["characters_auto"]]) + len([k for k in direction["characters"] if not k.startswith("_")])}')
    print('intensity: inferred from the writing in every scene without an authored cue sheet')


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else 'report'
    cat, sc = load_json(CATALOG), scenes()
    if os.path.exists(DIRECTION):
        direction = load_json(DIRECTION)
        for k, v in DEFAULT.items():
            direction.setdefault(k, v)
    else:
        direction = json.loads(json.dumps(DEFAULT))
    if cmd == 'suggest':
        nl, nc = suggest(direction, cat, sc)
        os.makedirs(os.path.dirname(DIRECTION), exist_ok=True)
        with open(DIRECTION, 'w', encoding='utf-8') as f:
            json.dump(direction, f, indent=1, ensure_ascii=False)
            f.write('\n')
        print(f'wrote {os.path.relpath(DIRECTION, GODOT)}: {nl} locale suggestions, {nc} character themes')
    elif cmd == 'validate':
        errors, warns = validate(direction, cat, sc)
        for w in warns:
            print('warning: ' + w)
        for e in errors:
            print('::error::music direction: ' + e)
        print(f'music direction: {len(errors)} error(s), {len(warns)} warning(s)')
        sys.exit(1 if errors else 0)
    elif cmd == 'report':
        report(direction, cat, sc)
    else:
        sys.exit(__doc__)


if __name__ == '__main__':
    main()
